sudo: false
cache: bundler
language: ruby
bundler_args: "--without development acceptance"
script: bundle exec rake validate lint
matrix:
  fast_finish: true
  include:
  - rvm: 2.2.5
    env: PUPPET_GEM_VERSION="~> 5.0" STRICT_VARIABLES="yes" DEPLOY_TO_FORGE="yes"
  - rvm: 2.2.5
    env: PUPPET_GEM_VERSION="~> 4.0" STRICT_VARIABLES="yes"
  - rvm: 2.1.6
    env: PUPPET_GEM_VERSION="~> 4.0" STRICT_VARIABLES="yes"
deploy:
  provider: puppetforge
  user: gnubilafrance
  password:
    secure: Jr2gk1aVstZ6RusmWChZFYfthV3wrl8FTPVuR09lrDVh3eyNJicOCS+FwCu2kXzFNFSzXGQpDWoLDNjqO7Tq/m75962wJkQdtDsivUnYKvmNWMvjI5cgDydqEcgDKxV3XtphMzpAILkr5IdfNGEV9AMXcsc/kp8UUInCaOgBDL0=
  on:
    tags: true
    all_branches: true
    condition: "$DEPLOY_TO_FORGE = yes"
